--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2 (Debian 12.2-2.pgdg100+1)
-- Dumped by pg_dump version 12.2

-- Started on 2020-04-23 11:47:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 211 (class 1259 OID 37383)
-- Name: RegisteredCredentials; Type: TABLE; Schema: public; Owner: docker
--

CREATE TABLE public."RegisteredCredentials" (
    "HashId" text NOT NULL,
    "Id" bigint NOT NULL,
    "CitizenAddress" text,
    "SubjectHashId" text NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "CredentialCreation" timestamp without time zone NOT NULL,
    "Sex" integer NOT NULL,
    "Location" public.geometry(Point),
    "Lat" double precision NOT NULL,
    "Lon" double precision NOT NULL,
    "CredentialType" integer NOT NULL,
    "Reason" integer NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "CountryGId" integer NOT NULL,
    "StateGId" integer NOT NULL,
    "HasNoSymptoms" boolean,
    "HasFever" boolean,
    "HasCought" boolean,
    "HasBreathingIssues" boolean,
    "HasSymptoms" boolean,
    "HasLossSmell" boolean,
    "HasHeadache" boolean,
    "HasMusclePain" boolean,
    "HasSoreThroat" boolean,
    "Age" smallint NOT NULL
);


ALTER TABLE public."RegisteredCredentials" OWNER TO docker;

--
-- TOC entry 210 (class 1259 OID 37381)
-- Name: RegisteredCredentials_Id_seq; Type: SEQUENCE; Schema: public; Owner: docker
--

ALTER TABLE public."RegisteredCredentials" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RegisteredCredentials_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4741 (class 0 OID 37383)
-- Dependencies: 211
-- Data for Name: RegisteredCredentials; Type: TABLE DATA; Schema: public; Owner: docker
--

COPY public."RegisteredCredentials" ("HashId", "Id", "CitizenAddress", "SubjectHashId", "StartDate", "CredentialCreation", "Sex", "Location", "Lat", "Lon", "CredentialType", "Reason", "IsRevoked", "CountryGId", "StateGId", "HasNoSymptoms", "HasFever", "HasCought", "HasBreathingIssues", "HasSymptoms", "HasLossSmell", "HasHeadache", "HasMusclePain", "HasSoreThroat", "Age") FROM stdin;
0x4a806fa6137e4325646e8f8814c4f719346d50c1bb056fcf78a2b031a6a584e0	21	0xbcEda2Ba9aF65c18C7992849C312d1Db77cF008E	0x4206fa6137e4325646e8f8814c4f718345d50c1bb056fcf78a2a031a6a584e1	2020-04-22 19:11:18	2020-04-22 19:11:18	1	010100000000000000823E52C000000000160443C0	-72.9766845703125	-38.03192138671875	1	3	f	3	1385	\N	\N	\N	\N	\N	\N	\N	\N	\N	15
0x45806fa6137e4325646e8f8814c4f719346d50c1bb056fcf78a2b031a6a584e0	22	0xb9Eda2Ba9aF65c18C7992849C312d1Db77cF008E	0x4806fa6137e4325646e8f8814c4f718345d50c1bb056fcf78a2a031a6a584e1	2020-04-22 19:11:18	2020-04-22 19:11:18	1	010100000000000000DE9751C00000000016BB40C0	-70.3729248046875	-33.46160888671875	2	0	f	3	1379	t	\N	\N	\N	\N	\N	\N	\N	\N	24
0x45806fa6137e432564638f8814c4f719346d50c1bb056fcf78a2b031a6a584e0	23	0xb9Eda2Ba9aF65c18C7912849C312d1Db77cF008E	0x4806fa6137e4322646e8f8814c4f718345d50c1bb056fcf78a2a031a6a584e1	2020-04-22 19:11:18	2020-04-22 19:11:18	0	010100000000000000EED251C000000000BE2141C0	-71.2957763671875	-34.26361083984375	2	0	f	3	1382	\N	\N	\N	\N	t	\N	t	\N	\N	35
0x45806fd6137e432564638f8814c4f719346d50c1bb056fcf78a2b031a6a584e0	24	0xb9Eda2Ba9aF65c18C7912849C312d1Db77cF008E	0x4805fa6137e4322646e8f8814c4f718345d50c1bb056fcf78a2a031a6a584e1	2020-04-22 19:11:18	2020-04-22 19:11:18	0	0101000000000000009C6849C000000000943439C0	-50.8172607421875	-25.20538330078125	2	0	f	46	798	\N	\N	\N	\N	t	t	t	\N	\N	44
\.


--
-- TOC entry 4747 (class 0 OID 0)
-- Dependencies: 210
-- Name: RegisteredCredentials_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: docker
--

SELECT pg_catalog.setval('public."RegisteredCredentials_Id_seq"', 24, true);


--
-- TOC entry 4602 (class 2606 OID 37390)
-- Name: RegisteredCredentials PK_RegisteredCredentials; Type: CONSTRAINT; Schema: public; Owner: docker
--

ALTER TABLE ONLY public."RegisteredCredentials"
    ADD CONSTRAINT "PK_RegisteredCredentials" PRIMARY KEY ("HashId");


--
-- TOC entry 4603 (class 1259 OID 62428)
-- Name: SubjectIdIdx; Type: INDEX; Schema: public; Owner: docker
--

CREATE INDEX "SubjectIdIdx" ON public."RegisteredCredentials" USING btree ("IsRevoked", "SubjectHashId" COLLATE "C.UTF-8" varchar_ops);


--
-- TOC entry 4604 (class 1259 OID 54398)
-- Name: fki_InCountry; Type: INDEX; Schema: public; Owner: docker
--

CREATE INDEX "fki_InCountry" ON public."RegisteredCredentials" USING btree ("CountryGId");


--
-- TOC entry 4605 (class 1259 OID 54404)
-- Name: fki_InState; Type: INDEX; Schema: public; Owner: docker
--

CREATE INDEX "fki_InState" ON public."RegisteredCredentials" USING btree ("StateGId");


--
-- TOC entry 4606 (class 2606 OID 54393)
-- Name: RegisteredCredentials InCountry; Type: FK CONSTRAINT; Schema: public; Owner: docker
--

ALTER TABLE ONLY public."RegisteredCredentials"
    ADD CONSTRAINT "InCountry" FOREIGN KEY ("CountryGId") REFERENCES public."Countries"(gid);


--
-- TOC entry 4607 (class 2606 OID 54399)
-- Name: RegisteredCredentials InState; Type: FK CONSTRAINT; Schema: public; Owner: docker
--

ALTER TABLE ONLY public."RegisteredCredentials"
    ADD CONSTRAINT "InState" FOREIGN KEY ("StateGId") REFERENCES public."States"(gid);


-- Completed on 2020-04-23 11:47:45

--
-- PostgreSQL database dump complete
--

