version: '3'

services:
  eventeum:
    image: eventeum/eventeum:latest
    ports:
    - "8060:8060"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: ${SPRING_DATA_MONGODB_HOST}
      SPRING_DATA_MONGODB_PORT: ${SPRING_DATA_MONGODB_PORT}
      ETHEREUM_NODE_URL: ${ETHEREUM_NODE_URL}
      BROADCASTER_TYPE: ${BROADCASTER_TYPE}
      BROADCASTER_HTTP_CONTRACTEVENTSURL: ${BROADCASTER_HTTP_CONTRACTEVENTSURL}
      BROADCASTER_HTTP_BLOCKEVENTSURL: ${BROADCASTER_HTTP_BLOCKEVENTSURL}
    networks:
      - default

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data/db:/data/db
    networks:
      - default

  postgres:
    image: kartoza/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
    networks:
      - default
