version: '3'

services:
  eventeum:
    image: eventeum/eventeum:latest
    ports:
    - "8060:8060"
    depends_on:
      - mongodb
      - david19-import
    environment:
      SPRING_DATA_MONGODB_HOST: ${SPRING_DATA_MONGODB_HOST}
      SPRING_DATA_MONGODB_PORT: ${SPRING_DATA_MONGODB_PORT}
      ETHEREUM_NODE_URL: ${ETHEREUM_NODE_URL}
      BROADCASTER_TYPE: ${BROADCASTER_TYPE}
      BROADCASTER_HTTP_CONTRACTEVENTSURL: ${BROADCASTER_HTTP_CONTRACTEVENTSURL}
      BROADCASTER_HTTP_BLOCKEVENTSURL: ${BROADCASTER_HTTP_BLOCKEVENTSURL}
    networks:
      - default

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data/db:/data/db
    networks:
      - default

  postgres:
    image: sabradevregistry01.azurecr.io/postgresql:base
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default

  david19-import:
    image: sabradevregistry01.azurecr.io/david19-import:1.0.0
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      DAVID19_API_CONNECTIONSTRINGS__DEFAULT: ${DAVID19_API_CONNECTIONSTRINGS__DEFAULT}
    networks:
      - default

  david19-api:
    image: sabradevregistry01.azurecr.io/david19-api:1.0.0
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
    environment:
      DAVID19_API_CONNECTIONSTRINGS__DEFAULT: ${DAVID19_API_CONNECTIONSTRINGS__DEFAULT}
    networks:
      - default